image: node:20

stages:
  - deploy

cache:
  paths:
    - frontend/node_modules/

deploy_frontend_vercel:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  before_script:
    - npm install -g vercel
  script:
    - cd frontend
    - npm.cmd install
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
